import "@fontsource/roboto/300.css"
import "@fontsource/roboto/400.css"
import "@fontsource/roboto/500.css"
import "@fontsource/roboto/700.css"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import { ThemeProvider } from "@mui/material/styles"
import { Refine, ResourceProps } from "@refinedev/core"
import { RefineSnackbarProvider } from "@refinedev/mui"
import routerProvider from "@refinedev/nextjs-router"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { authProvider } from "providers/auth"
import theme from "../theme"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const refineResource: ResourceProps[] = []

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <RefineSnackbarProvider>
              <Refine
                authProvider={authProvider}
                routerProvider={routerProvider}
                resources={refineResource}
                options={{ syncWithLocation: true }}
              >
                {children}
              </Refine>
            </RefineSnackbarProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
